### PR TITLE
changes for keras 2.4.3 and tf 2.4.1

### PR DESCRIPTION
**Pull request by ratmcu**
Fixed few complains on the type mismatch of tensors and arguments for creating tensors. Also a failed assertion was omitted. 
Code works and trains. Would be helpful if these changes are to be reviewed.

### CODE REVIEW

**Comment by tkipf** [comment]
Thanks a lot! I'll try to have a look soon.

**Comment by tkipf** [comment]
I'll leave this open for now, so anyone can patch/merge it locally if they need these updates. I'm unable to test the commit right now, but I would nonetheless recommend to clean it up somewhat and remove commented out blocks and print statements.

**Comment by ratmcu** [comment]
Thanks, I cleaned up the code. Hopefully it can be used by:
`pip install git+https://github.com/ratmcu/keras-gcn.git`

**Comment by utkarsh0902311047** [comment]
Hi @ratmcu . Using your github code for Keras-GCN the test accuracy achieved is only 32.3%. Am I missing something or why is it so?

**Pull request closed without merging**
